-- SeatAware route seed data
-- Assumes transport_types IDs:
-- 1 = Bus, 2 = Luas, 3 = Train, 4 = DART
-- Run after creating the routes and transport_types tables.

USE seataware_db;

INSERT INTO routes (transport_type_id, route_name, operator_name)
VALUES
(1, '1', 'Dublin Bus'),
(1, '4', 'Dublin Bus'),
(1, '7', 'Dublin Bus'),
(1, '7A', 'Dublin Bus'),
(1, '9', 'Dublin Bus'),
(1, '11', 'Dublin Bus'),
(1, '13', 'Dublin Bus'),
(1, '14', 'Dublin Bus'),
(1, '15', 'Dublin Bus'),
(1, '15A', 'Dublin Bus'),
(1, '15B', 'Dublin Bus'),
(1, '16', 'Dublin Bus'),
(1, '25', 'Dublin Bus'),
(1, '25A', 'Dublin Bus'),
(1, '25B', 'Dublin Bus'),
(1, '25D', 'Dublin Bus'),
(1, '25X', 'Dublin Bus'),
(1, '26', 'Dublin Bus'),
(1, '27', 'Dublin Bus'),
(1, '27A', 'Dublin Bus'),
(1, '27B', 'Dublin Bus'),
(1, '27X', 'Dublin Bus'),
(1, '31', 'Dublin Bus'),
(1, '31A', 'Dublin Bus'),
(1, '31B', 'Dublin Bus'),
(1, '32', 'Dublin Bus'),
(1, '32X', 'Dublin Bus'),
(1, '33', 'Dublin Bus'),
(1, '33A', 'Dublin Bus'),
(1, '33B', 'Dublin Bus'),
(1, '33D', 'Dublin Bus'),
(1, '33E', 'Dublin Bus'),
(1, '33X', 'Dublin Bus'),
(1, '37', 'Dublin Bus'),
(1, '38', 'Dublin Bus'),
(1, '38A', 'Dublin Bus'),
(1, '38B', 'Dublin Bus'),
(1, '38D', 'Dublin Bus'),
(1, '39', 'Dublin Bus'),
(1, '39A', 'Dublin Bus'),
(1, '39X', 'Dublin Bus'),
(1, '40', 'Dublin Bus'),
(1, '40B', 'Dublin Bus'),
(1, '40D', 'Dublin Bus'),
(1, '40E', 'Dublin Bus'),
(1, '41', 'Dublin Bus'),
(1, '41B', 'Dublin Bus'),
(1, '41C', 'Dublin Bus'),
(1, '41D', 'Dublin Bus'),
(1, '41X', 'Dublin Bus'),
(1, '42', 'Dublin Bus'),
(1, '43', 'Dublin Bus'),
(1, '44', 'Dublin Bus'),
(1, '46A', 'Dublin Bus'),
(1, '47', 'Dublin Bus'),
(1, '49', 'Dublin Bus'),
(1, '51D', 'Dublin Bus'),
(1, '51X', 'Dublin Bus'),
(1, '53', 'Dublin Bus'),
(1, '54A', 'Dublin Bus'),
(1, '56A', 'Dublin Bus'),
(1, '61', 'Dublin Bus'),
(1, '65', 'Dublin Bus'),
(1, '65B', 'Dublin Bus'),
(1, '66', 'Dublin Bus'),
(1, '66A', 'Dublin Bus'),
(1, '66B', 'Dublin Bus'),
(1, '66E', 'Dublin Bus'),
(1, '66X', 'Dublin Bus'),
(1, '67', 'Dublin Bus'),
(1, '67X', 'Dublin Bus'),
(1, '68', 'Dublin Bus'),
(1, '68A', 'Dublin Bus'),
(1, '69', 'Dublin Bus'),
(1, '69X', 'Dublin Bus'),
(1, '70', 'Dublin Bus'),
(1, '77A', 'Dublin Bus'),
(1, '77X', 'Dublin Bus'),
(1, '79', 'Dublin Bus'),
(1, '79A', 'Dublin Bus'),
(1, '83', 'Dublin Bus'),
(1, '83A', 'Dublin Bus'),
(1, '84', 'Dublin Bus'),
(1, '84A', 'Dublin Bus'),
(1, '84X', 'Dublin Bus'),
(1, '102', 'Dublin Bus'),
(1, '104', 'Dublin Bus'),
(1, '111', 'Dublin Bus'),
(1, '114', 'Dublin Bus'),
(1, '116', 'Dublin Bus'),
(1, '118', 'Dublin Bus'),
(1, '120', 'Dublin Bus'),
(1, '122', 'Dublin Bus'),
(1, '123', 'Dublin Bus'),
(1, '130', 'Dublin Bus'),
(1, '140', 'Dublin Bus'),
(1, '142', 'Dublin Bus'),
(1, '145', 'Dublin Bus'),
(1, '150', 'Dublin Bus'),
(1, '151', 'Dublin Bus'),
(1, '155', 'Dublin Bus'),
(1, '184', 'Dublin Bus'),
(1, '185', 'Dublin Bus'),
(1, 'C1', 'Dublin Bus'),
(1, 'C2', 'Dublin Bus'),
(1, 'C3', 'Dublin Bus'),
(1, 'C4', 'Dublin Bus'),
(1, 'C5', 'Dublin Bus'),
(1, 'C6', 'Dublin Bus'),
(1, 'G1', 'Dublin Bus'),
(1, 'G2', 'Dublin Bus'),
(1, 'H1', 'Dublin Bus'),
(1, 'H2', 'Dublin Bus'),
(1, 'H3', 'Dublin Bus'),
(1, 'N4', 'Dublin Bus'),
(1, 'N6', 'Dublin Bus'),
(1, 'S2', 'Dublin Bus'),
(1, 'S4', 'Dublin Bus'),
(1, 'S6', 'Dublin Bus'),
(1, 'S8', 'Dublin Bus'),
(1, 'W2', 'Dublin Bus'),
(1, 'W4', 'Dublin Bus'),
(1, 'W6', 'Dublin Bus'),
(1, '17', 'Go-Ahead Ireland'),
(1, '17A', 'Go-Ahead Ireland'),
(1, '18', 'Go-Ahead Ireland'),
(1, '45A', 'Go-Ahead Ireland'),
(1, '59', 'Go-Ahead Ireland'),
(1, '63', 'Go-Ahead Ireland'),
(1, '75', 'Go-Ahead Ireland'),
(1, '76', 'Go-Ahead Ireland'),
(1, '76A', 'Go-Ahead Ireland'),
(1, '102', 'Go-Ahead Ireland'),
(1, '104', 'Go-Ahead Ireland'),
(1, '111', 'Go-Ahead Ireland'),
(1, '175', 'Go-Ahead Ireland'),
(1, '184', 'Go-Ahead Ireland'),
(1, '185', 'Go-Ahead Ireland'),
(1, '220', 'Go-Ahead Ireland'),
(1, '220A', 'Go-Ahead Ireland'),
(1, '236', 'Go-Ahead Ireland'),
(1, '238', 'Go-Ahead Ireland'),
(1, '239', 'Go-Ahead Ireland'),
(1, '270', 'Go-Ahead Ireland'),
(1, '270A', 'Go-Ahead Ireland'),
(1, '2 Dublin Airport to Wexford', 'Bus Éireann'),
(1, '4 Dublin to Waterford', 'Bus Éireann'),
(1, '5 Dublin to New Ross', 'Bus Éireann'),
(1, '13 Limerick to Tralee', 'Bus Éireann'),
(1, '14 Limerick to Killarney', 'Bus Éireann'),
(1, '20 Galway to Dublin', 'Bus Éireann'),
(1, '22 Dublin to Ballina', 'Bus Éireann'),
(1, '23 Dublin to Sligo', 'Bus Éireann'),
(1, '30 Dublin to Donegal', 'Bus Éireann'),
(1, '32 Dublin to Letterkenny', 'Bus Éireann'),
(1, '40 Waterford to Tralee', 'Bus Éireann'),
(1, '51 Cork to Galway', 'Bus Éireann'),
(1, '55 Limerick to Waterford', 'Bus Éireann'),
(1, '64 Galway to Derry', 'Bus Éireann'),
(1, '65 Galway to Cavan', 'Bus Éireann'),
(1, '70 Athlone to Mullingar', 'Bus Éireann'),
(1, '72 Limerick to Athlone', 'Bus Éireann'),
(1, '73 Waterford to Athlone', 'Bus Éireann'),
(1, '100 Drogheda to Dundalk', 'Bus Éireann'),
(1, '100X Dublin to Dundalk', 'Bus Éireann'),
(1, '101 Dublin to Drogheda', 'Bus Éireann'),
(1, '101X Dublin to Drogheda', 'Bus Éireann'),
(1, '103 Dublin to Ratoath', 'Bus Éireann'),
(1, '103X Dublin to Navan', 'Bus Éireann'),
(1, '105 Blanchardstown to Drogheda', 'Bus Éireann'),
(1, '107 Navan to Kingscourt', 'Bus Éireann'),
(1, '109 Dublin to Kells', 'Bus Éireann'),
(1, '109A Dublin Airport to Kells', 'Bus Éireann'),
(1, '109B Dublin to Trim', 'Bus Éireann'),
(1, '109X Dublin to Cavan', 'Bus Éireann'),
(1, '115 Dublin to Mullingar', 'Bus Éireann'),
(1, '126 Dublin to Kildare', 'Bus Éireann'),
(1, '130 Kilcullen to Newbridge', 'Bus Éireann'),
(1, '131 Bray to Wicklow', 'Bus Éireann'),
(1, '132 Dublin to Bunclody', 'Bus Éireann'),
(1, '133 Dublin to Wicklow', 'Bus Éireann'),
(1, '133X Dublin to Wicklow', 'Bus Éireann'),
(1, '201 CUH to Boherboy Road', 'Bus Éireann'),
(1, '202 Hollyhill to Mahon Point', 'Bus Éireann'),
(1, '203 Manor Farm to Parklands', 'Bus Éireann'),
(1, '205 MTU to Kent Station', 'Bus Éireann'),
(1, '206 Grange to South Mall', 'Bus Éireann'),
(1, '207 Donnybrook to Glenheights', 'Bus Éireann'),
(1, '208 Ashmount to Curraheen', 'Bus Éireann'),
(1, '209 Lotamore to St Patrick Street', 'Bus Éireann'),
(1, '212 Kent Station to Mahon Point', 'Bus Éireann'),
(1, '214 CUH to Glanmire', 'Bus Éireann'),
(1, '215 Jacobs Island to Blarney', 'Bus Éireann'),
(1, '220 Carrigaline to Ballincollig', 'Bus Éireann'),
(1, '221 Glanmire to Haulbowline', 'Bus Éireann'),
(1, '225 Cork Airport to Haulbowline', 'Bus Éireann'),
(1, '226 Cork Airport to Kinsale', 'Bus Éireann'),
(1, '301 Westbury to Regional Hospital', 'Bus Éireann'),
(1, '302 Caherdavin to City Centre', 'Bus Éireann'),
(1, '303 Pineview to Southill', 'Bus Éireann'),
(1, '304 Raheen to University of Limerick', 'Bus Éireann'),
(1, '304A Raheen to University of Limerick', 'Bus Éireann'),
(1, '305 St Marys Park to Lynwood Park', 'Bus Éireann'),
(1, '306 Ballynanty to Lord Edward Street', 'Bus Éireann'),
(1, '307 City Centre to Castletroy', 'Bus Éireann'),
(1, '308 City Centre to University of Limerick', 'Bus Éireann'),
(1, '401 Salthill to Eyre Square', 'Bus Éireann'),
(1, '402 Seacrest to Merlin Park', 'Bus Éireann'),
(1, '404 Oranmore to Newcastle', 'Bus Éireann'),
(1, '405 Ballybane to Rahoon', 'Bus Éireann'),
(1, '407 Eyre Square to Bóthar an Chóiste', 'Bus Éireann'),
(1, '409 Parkmore to Eyre Square', 'Bus Éireann'),
(1, 'W1 Waterford City Service', 'Bus Éireann'),
(1, 'W2 Waterford City Service', 'Bus Éireann'),
(1, 'W3 Waterford City Service', 'Bus Éireann'),
(1, 'W4 Waterford City Service', 'Bus Éireann'),
(1, 'W5 Waterford City Service', 'Bus Éireann'),
(1, 'TFI Local Link 183 Arklow to Gorey', 'TFI Local Link'),
(1, 'TFI Local Link 196 Gorey to Carnew', 'TFI Local Link'),
(1, 'TFI Local Link 817 Athy to Portlaoise', 'TFI Local Link'),
(1, 'TFI Local Link 823 Birr to Portlaoise', 'TFI Local Link'),
(1, 'TFI Local Link 929 Cavan to Monaghan', 'TFI Local Link'),
(1, 'TFI Local Link 975 Longford to Cavan', 'TFI Local Link'),
(2, 'Green Line', 'Luas'),
(2, 'Red Line', 'Luas'),
(3, 'Dublin to Cork', 'Irish Rail'),
(3, 'Dublin to Galway', 'Irish Rail'),
(3, 'Dublin to Limerick', 'Irish Rail'),
(3, 'Dublin to Waterford', 'Irish Rail'),
(3, 'Dublin to Belfast', 'Irish Rail'),
(3, 'Dublin to Sligo', 'Irish Rail'),
(3, 'Dublin to Westport', 'Irish Rail'),
(3, 'Dublin to Ballina', 'Irish Rail'),
(3, 'Dublin to Tralee', 'Irish Rail'),
(3, 'Dublin to Rosslare', 'Irish Rail'),
(3, 'Cork to Cobh', 'Irish Rail'),
(3, 'Cork to Midleton', 'Irish Rail'),
(3, 'Limerick to Galway', 'Irish Rail'),
(3, 'Limerick to Ennis', 'Irish Rail'),
(3, 'Limerick Junction to Waterford', 'Irish Rail'),
(3, 'Northern Commuter', 'Irish Rail'),
(3, 'Western Commuter', 'Irish Rail'),
(3, 'South Western Commuter', 'Irish Rail'),
(3, 'South Eastern Commuter', 'Irish Rail'),
(3, 'Maynooth Commuter', 'Irish Rail'),
(3, 'Portlaoise Commuter', 'Irish Rail'),
(3, 'M3 Parkway Commuter', 'Irish Rail'),
(3, 'Drogheda Commuter', 'Irish Rail'),
(3, 'Dundalk Commuter', 'Irish Rail'),
(3, 'Kildare Commuter', 'Irish Rail'),
(4, 'DART Northbound', 'Irish Rail'),
(4, 'DART Southbound', 'Irish Rail'),
(4, 'DART Howth Branch', 'Irish Rail'),
(4, 'DART Malahide Branch', 'Irish Rail'),
(4, 'DART Bray Service', 'Irish Rail'),
(4, 'DART Greystones Service', 'Irish Rail');

-- Check imported routes
SELECT COUNT(*) AS total_routes FROM routes;
SELECT * FROM routes ORDER BY operator_name, route_name;
